### ISSUE TITLE
Multiple issues when predict generates from a slow model (qwen2.5-coder:32b)

### ISSUE THREAD

**Issue by battmanux** [hand-e-fr/OpenHosta#179]
When generating a dataset on a local gpu with ollama, generation can be slow and trigger api_call timeout. 

There are several improvements that can be done to help the user diagnose the isse.

logs:
```python
>>> average_temperature_by_country(2021, 4, "FR")
[Architecture] not found
[Debug] Model with input size 3 and output size 1
[Model] Type : LinearRegression
[Architecture] saved to /home/user/__hostacache__/average_temperature_by_country/model.json
[Weights] not found
[Data] not found
[Dataset] not found, generate data
[Data Generation] Error during generation: [Model.api_call] Request failed:
HTTPConnectionPool(host='localhost', port=11434): Read timed out. (read timeout=30)


 line 191
[Dataset] generated and saved at /home/user/__hostacache__/average_temperature_by_country/generated_data.csv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in average_temperature_by_country
  File "/home/user/venv_openhosta/lib/python3.11/site-packages/OpenHosta/exec/predict/predict.py", line 50, in predict
    train_model(config, memory, hosta_model, oracle, func, logger)
  File "/home/user/venv_openhosta/lib/python3.11/site-packages/OpenHosta/exec/predict/predict.py", line 128, in train_model
    train_set, val_set = prepare_dataset(config, memory, func, oracle, model, logger)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/venv_openhosta/lib/python3.11/site-packages/OpenHosta/exec/predict/predict.py", line 174, in prepare_dataset
    dataset.tensorize()
  File "/home/user/venv_openhosta/lib/python3.11/site-packages/OpenHosta/exec/predict/dataset/dataset.py", line 118, in tensorize
    if value[0].output is None:
       ~~~~~^^^
IndexError: list index out of range
```

## 1.  Suggest Model(timout=...)

when `Read timed out` error is raised,  api_cal could suggest to increase the parameter in Model(timeout=...)

## 2. Test for empty training set in predict

value len is not tested before value[0] call

## 3. _generate_data default slice could be configurable or linked to timeout

in predict.py:
`request_amounts = int(config.generated_data / 100) if config.generated_data > 100 else 1`

100 seems to be arbitrary and could be reduced instead of augmenting timout value. The way it is implemented, it is not configurable.

# Workaround

increase timout to 600 when configuring Model
call dataset = generate_data(average_temperature_by_country, 50) multiple times and aggregate by hand.

**Comment by battmanux** [comment]
done in v4 refactoring using GuardedTypes
